variables:
  clippy_toolchain: 1.36.0
  minimum_toolchain: 1.36.0

jobs:
- job: MacOS
  pool:
    vmImage: macOS-10.13
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
    - template: admin/pipelines/macos-tests.yml
