[package]
name = "rustls-native-certs"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
edition = "2018"

[dependencies]
rustls = "0.16.0"

[dev-dependencies]
webpki = "0.21"

[target.'cfg(windows)'.dependencies]
schannel = "0.1.15"

[target.'cfg(target_os = "linux")'.dependencies]
openssl-probe = "0.1.2"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.3.1"
